# MNIST NN ( NN )
MNIST NN 클래스(모듈)형식


In [2]:
from __future__ import absolute_import, division, print_function, unicode_literals
import tensorflow as tf

## 1. 데이터 로드 & 전처리

In [13]:
def load_mnist():
    (train_x, train_y), (test_x, test_y) = tf.keras.datasets.mnist.load_data()
    # as_dtype & normalize
    train_x = tf.constant(train_x, dtype=tf.float32) / 255.0
    test_x = tf.constant(test_x, dtype=tf.float32) / 255.0
    
    # expand_dims ( image )
    train_x = tf.expand_dims(train_x, axis=-1) # [N, 28, 28] -> [N, 28, 28, 1]
    test_x = tf.expand_dims(test_x, axis=-1) # [N, 28, 28] -> [N, 28, 28, 1]
    
    # label one-hot encoding
    train_y = tf.one_hot(train_y, depth = 10)
    test_y = tf.one_hot(test_y, depth = 10)
    
    return train_x, train_y, test_x, test_y

train_X, train_Y, test_X, test_Y = load_mnist()



tf.Tensor(
[[0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]], shape=(60000, 10), dtype=float32)
